config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end  

  scope "(:locale)", locale: /en|ru/ do
    devise_for :users, controllers: { registrations: 'registrations' }
    root to: 'public#index', as: :localized_root
  end

  root to: 'categories#index'
  
  post :set_timezone, to: 'application#set_timezone'

  get "/service-worker.js", to: "service_worker#service_worker"
  get "/manifest.json", to: "service_worker#manifest"

  namespace :admin do
    resources :users, only: :index
  end

  resource :profile, only: [:show, :update]
  resource :timeline, only: [:update]

  resources :analytics, only: [:index] do
    collection do
      post '/get-chart-donut-time-categories-data', to: 'analytics#chart_donut_time_categories_data'
      post '/get-chart-bar-hourly-activity-data', to: 'analytics#chart_bar_hourly_activity_data'
    end
  end

  resources :categories, except: :index do
    patch :update_position, on: :member
    post :report_modal_content, on: :member
  end
  get :tracker, to: 'categories#index'

  resources :periods, except: :show do
    post :run, on: :collection
    post :stop, on: :collection
  end

  resources :goals

  resources :reports, param: :unique_identifier do
    post :access_report, on: :member
    post :deletion_confirmation_modal_content, on: :member
  end

  resources :subscriptions, only: [] do
    post :toggle_channel, on: :collection
  end

  post '/telegram/webhook', to: 'telegram#webhook'
end

app/models/period.rb
class Period < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :start, presence: true
  validate :no_overlap, on: [:create, :update]

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "end", "id", "id_value", "start", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category", "user"]
  end

  def formatted_time(total_seconds = nil)
    total_seconds = total_seconds || (actual_end - self.start).to_i
    CategoriesAnalyticsService.seconds_to_time_format(total_seconds)
  end

  def actual_end
    self.end || Time.now
  end

  def start_in_zone
    self.start&.in_time_zone
  end

  def end_in_zone
    self.end&.in_time_zone
  end

  def duration
    actual_end - start
  end

  def total_seconds_for_date(date)
    total_seconds = 0

    day_start = date.beginning_of_day
    day_end = date.end_of_day
    
    period_start = [self.start, day_start].max
    period_end = [actual_end, day_end].min
    
    total_seconds += [period_end - period_start, 0].max if period_start < period_end

    total_seconds
  end

  def self.expand_periods(periods)
    expanded_periods = []
  
    periods.each do |period|
      (period.start.to_date..period.actual_end.to_date).each do |date|
        expanded_periods << { date: date, period: period }
      end
    end
  
    expanded_periods
  end

  def self.group_periods_by_date(periods)
    grouped_periods = expand_periods(periods).group_by { |p| p[:date] }

    # Sort the grouped periods by date in descending order (from most recent to oldest)
    sorted_grouped_periods = grouped_periods.sort_by { |date, _periods| -date.to_time.to_i }.to_h

    sorted_grouped_periods.transform_values { |periods| periods.map { |p| p[:period] } }
  end

  def self.group_periods_by_date_with_limits(periods, start_date, end_date)
    filtered_periods = filter_periods_by_date_limits(periods, start_date, end_date)
    grouped_periods = expand_periods_with_limits(filtered_periods).group_by { |p| p[:date] }

    # Sort the grouped periods by date in descending order (from most recent to oldest)
    sorted_grouped_periods = grouped_periods.sort_by { |date, _periods| -date.to_time.to_i }.to_h

    sorted_grouped_periods.transform_values { |periods| periods.map { |p| p[:period] } }
  end

  def formatted_time_for_date(date)
    if self.start.to_date != date && actual_end.to_date != date
      seconds = 60 * 60 * 24 # full day
    elsif self.start.to_date != date
      seconds = (actual_end - date.beginning_of_day).to_f
    elsif actual_end.to_date != date
      seconds = (date.end_of_day - self.start).to_f
    end

    formatted_time(seconds)
  end

  def calculate_seconds_for_date(date)
    day_start = date.beginning_of_day
    day_end = date.end_of_day
  
    return 0 if self.start > day_end || (self.end && self.end < day_start)
  
    period_start = [self.start, day_start].max
    period_end = [(self.end || Time.current), day_end].min
  
    (period_end - period_start).to_i
  end

  private

  def no_overlap
    return if user.nil?

    overlapping_periods = user.periods.where.not(id: id)
    overlapping_periods = overlapping_periods.where('start < ? AND ("end" > ? OR "end" IS NULL)', actual_end, self.start)

    if overlapping_periods.exists?
      errors.add(:base, I18n.t('activerecord.errors.messages.overlaps'))
    end
  end

  def self.filter_periods_by_date_limits(periods, start_date, end_date)
    periods.flat_map do |period|
      adjusted_periods = []

      if period.start < start_date && period.end > end_date
        adjusted_periods << { period: period, start: start_date, end: end_date }
      elsif period.start < start_date && period.end > start_date
        adjusted_periods << { period: period, start: start_date, end: period.end }
      elsif period.start < end_date && period.end > end_date
        adjusted_periods << { period: period, start: period.start, end: end_date }
      elsif period.start >= start_date && period.end <= end_date
        adjusted_periods << { period: period, start: period.start, end: period.end }
      end

      adjusted_periods
    end
  end

  def self.expand_periods_with_limits(periods)
    periods.map do |period|
      (period[:start].to_date..period[:end].to_date).map do |date|
        { date: date, period: period[:period] }
      end
    end.flatten
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :find_period, only: [:edit, :update, :destroy]
  before_action :set_title, only: [:index, :new, :edit]
  
  include Authorizable
  include Pagy::Backend

  def index
    @q = current_user.periods.includes(:category).ransack(params[:q])

    periods = @q.result.order(start: :desc)

    @categories = current_user.categories
                              .joins(:periods)
                              .where.not(level: 0)
                              .distinct

    grouped_periods = Period.group_periods_by_date(periods)
    @pagy, @grouped_periods = pagy_array(grouped_periods.to_a)
  end

  def new
    @period = current_user.periods.new
    @categories = current_user.categories.select { |category| category.can_have_timer? }
  end

  def create
    if period_params[:start].blank?
      flash[:alert] = t('.start_date_is_missing')
      redirect_to new_period_path
      return
    end

    if period_params[:end].blank? && Category.any_unfinished_periods_for_user(current_user)
      flash[:alert] = t('.end_date_is_missing')
      redirect_to new_period_path
      return
    end

    @period = current_user.periods.new(period_params)

    start_time = DateTime.parse(period_params[:start])
    end_time = period_params[:end].present? ? DateTime.parse(period_params[:end]) : 0

    if (start_time < end_time || (end_time.is_a?(Numeric) && end_time.zero?)) && @period.save
      redirect_to periods_path, success: t('.period_success')
    else
      @categories = current_user.categories.select { |category| category.can_have_timer? }
      render :new
    end
  end

  def edit
    @categories = current_user.categories.select { |category| category.can_have_timer? }
  end

  def update
    if period_params[:start].blank?
      flash[:alert] = t('.start_date_is_missing')
      redirect_to edit_period_path
      return
    end

    if period_params[:end].blank? && current_user.periods.where(end: nil).first != @period
      flash[:alert] = t('.end_date_is_missing')
      redirect_to edit_period_path
      return
    end
    
    start_time = DateTime.parse(period_params[:start])
    end_time = period_params[:end].present? ? DateTime.parse(period_params[:end]) : 0

    if (start_time < end_time || (end_time.is_a?(Numeric) && end_time.zero?)) && @period.update(period_params)
      redirect_to periods_path, success: t('.period_success')
    else
      @categories = current_user.categories.select { |category| category.can_have_timer? }
      render :edit
    end
  end

  def destroy
    return if @period.blank?
    
    if @period.destroy
      redirect_to periods_path, notice: t('.period_success')
    else
      redirect_to periods_path, alert: 'Period was not deleted'
    end
  end

  def run
    @period = Period.new(period_params)
    @period.start = DateTime.current
    @period.user_id = current_user.id

    if @period.save
      prepare_and_respond
    else
      redirect_to tracker_path, alert: 'Something go wrong'
    end
  end

  def stop
    @category = current_user.categories.find(period_params[:category_id])
    return unless @category

    @period = @category.periods.find(params[:period_id])
    @period.end = DateTime.current
    @period.user_id = current_user.id

    if @period.save
      prepare_and_respond
    else
      redirect_to tracker_path, alert: 'Period was not saved'
    end
  end

  private

  def period_params
    params.require(:period).permit(:start, :end, :category_id)
  end

  def find_period
    @period = Period.find(params[:id])
  end

  def set_title
    @page_title = t('.title')
  end

  def prepare_and_respond
    @categories = current_user.categories.where(parent_id: nil)
    @unfinished_period = Category.any_unfinished_periods_for_user(current_user)
    @categories_for_timeline = current_user.categories_for_timeline

    total_seconds_today = current_user.periods.sum { |period| period.total_seconds_for_date(Time.now.to_date) }
    @total_time_for_today = CategoriesAnalyticsService.seconds_to_time_format(total_seconds_today, true)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to tracker_path }
    end
  end
end

app/helpers/periods_helper.rb
module PeriodsHelper
  def total_seconds_for_date(date, periods)
    total_seconds = 0

    periods.each do |period|
      next if period.end.blank?
      day_start = date.beginning_of_day
      day_end = date.end_of_day
      
      period_start = [period.start, day_start].max
      period_end = [period.end, day_end].min
      
      total_seconds += [period_end - period_start, 0].max if period_start < period_end
    end

    total_seconds
  end

  def daily_period_ratio(date, period, periods)
    (period.calculate_seconds_for_date(date) / total_seconds_for_date(date, periods) * 100).round(2)
  end

  def format_period_end(period, date)
    period_ends_in_date = period.actual_end.to_date == date

    if period_ends_in_date
      period.end ? period.end.strftime('%H:%M') : '...'
    else
      '24:00'
    end
  end

  def format_period_start(period, date)
    period.start.to_date == date ? period.start.strftime('%H:%M') : '00:00'
  end

  def daily_periods_time(periods, date)
    total_seconds = daily_periods_seconds(periods, date)
    humanize_time_from_seconds(total_seconds)
  end

  def daily_periods_seconds(periods, date)
    periods.sum { |period| period.total_seconds_for_date(date) }
  end

  def humanize_time_from_seconds(total_seconds)
    CategoriesAnalyticsService.seconds_to_time_format(total_seconds, true)
  end
end

app/views/periods/_form.html.erb
<div class="mt-8 max-w-3xl mx-auto grid grid-cols-1 gap-6 lg:max-w-7xl lg:grid-flow-col-dense lg:grid-cols-3">
  <div class="space-y-6 lg:col-start-1 lg:col-span-2">
    <%= form_with model: period, method: method, data: { turbo: false } do |f| %>
      <%= render 'shared/error_messages', resource: period %>
      <div class="mt-8 relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :start, t('.start'), class: 'absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-900' %>
        <%= f.text_field :start, data: { controller: 'flatpickr' }, value: period.start ? format_utc_datetime(period.start_in_zone) : nil, class: 'block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' %>
      </div>
    
      <div class="mt-6 relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :end, t('.end'), class: 'absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-900' %>
        <%= f.text_field :end, data: { controller: 'flatpickr' }, value: period.end ? format_utc_datetime(period.end_in_zone) : nil, class: 'block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' %>
      </div>
      <div class="mt-2 text-xs text-gray-500">
        <%= t('.blank_end_hint').html_safe %>
      </div>
    
      <div class="relative mt-8 border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :category_id, t('.category'), class: "absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-900" %>
        <%= f.select :category_id, options_from_collection_for_select(categories, :id, :name, period.category ? period.category.id : nil), { prompt: t('.choose_category') }, { class: 'block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' } %>
      </div>
    
      <div class="pt-5">
        <div class="flex">
          <%= link_to t(:cancel), periods_path, class: 'bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
          <%= f.submit btn_text, class: 'ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/periods/edit.html.erb
<%= render 'periods/form', period: @period, categories: @categories, method: :patch, btn_text: t(:update) %>

app/views/periods/index.html.erb
<div class="flex items-center mt-8">
  <div class="flex-auto">
    <%= search_form_for @q, data: { turbo_frame: :results, turbo_action: 'advance' }, target: '_top' do |f| %>
        <%= f.select :category_name_eq, options_from_collection_for_select(@categories, :name, :name, params.dig(:q, :category_name_eq)), { include_blank: t('.all_categories') }, class: "block w-auto py-2 pl-3 pr-8 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", onchange: 'this.form.requestSubmit()' %>
    <% end %>
  </div>
  <div>
    <%= link_to t('.new_period'), new_period_path, class: 'inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto' %>
  </div>
</div>
<div data-controller="confirmation" class="mt-2 flex flex-col">
  <%= turbo_frame_tag :results do %>
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">  
          <table id="periods_list" class="min-w-full">
            <thead class="bg-white">
              <tr>
                <th scope="col" width="20%" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%= t('.category')%></th>
                <th scope="col" width="20%" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.period') %></th>
                <th scope="col" width="20%" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.ratio') %></th>
                <th scope="col" width="20%" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.duration')%></th>
                <th scope="col" width="20%" class="px-3 py-3.5 text-sm font-semibold text-gray-900"></th>
              </tr>
            </thead>
            <tbody class="bg-white">
              <% @grouped_periods.each do |date, periods| %>
                <tr class="border-t border-gray-200">
                  <th colspan="4" scope="colgroup" class="bg-gray-50 px-4 py-2 text-left text-sm font-semibold text-gray-900 sm:px-6">
                    <%= humanize_date(date) %>
                  </th>
                  <th class="bg-gray-50 px-4 py-2 text-right text-xs font-normal text-gray-900 sm:px-6">
                    <%= daily_periods_time(periods, date) %>
                  </th>
                </tr>
                <% periods.each do |period| %>
                  <tr class="border-t border-gray-200">
                    <td class="relative py-3 pl-4 pr-3 text-xs text-gray-900 sm:pl-6">
                      <div class="flex items-center text-left">
                        <%= period.category.name %>
                        <% if period.end.blank? %>
                          <div class="neomorph-spinner ml-2">
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                          </div>
                        <% end %>
                        <% if period.start.to_date != period.actual_end.to_date %>
                          <div class="group relative">
                            <%= inline_svg('icons/arrow-3.svg', class: 'w-3 h-3 fill-current text-red-400 ml-2') %>
                            <span class="pointer-events-none absolute bg-black text-2xs leading-4 text-white rounded-md px-3 py-1 left-0 bottom-6 w-60 opacity-0 transition-opacity group-hover:opacity-100">
                              <%= t('.long_period_explanation') %>
                            </span>
                          </div>
                        <% end %>
                      </div>
                    </td>
                    <td class="whitespace-nowrap px-3 py-3 text-left text-xs text-gray-500">
                      <%= format_period_start(period, date) %> - <%= format_period_end(period, date) %>
                    </td>
                    <td class="whitespace-nowrap px-3 py-3 text-left text-xs text-gray-500">
                      <% if periods.size > 1 %>
                        <div class="relative max-w-32 h-2 border border-gray-200 rounded-full bg-gray-100">
                          <div 
                          class="group absolute h-full bg-purple-600 rounded-full"
                          style="width: <%= period.end ? daily_period_ratio(date, period, periods) : 0 %>%;">
                            <span class="pointer-events-none absolute bg-black text-2xs leading-4 text-white rounded-md px-3 py-1 bottom-3 left-0 w-max opacity-0 transition-opacity group-hover:opacity-100">
                              <%= t('.ratio') %>: <%= period.end ? daily_period_ratio(date, period, periods) : 0 %>%
                            </span>
                          </div>
                        </div>
                      <% end %>
                    </td>
                    <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500">
                      <div class="flex items-center">
                        <%= inline_svg('icons/clock.svg', class: 'w-4 h-4 fill-current text-purple-600 mr-2') %>
                        <%= period.formatted_time_for_date(date) %>
                      </div>
                    </td>
                    <td class="whitespace-nowrap px-4 py-3 text-right text-sm text-gray-500 sm:px-6">
                      <div class="relative flex items-center justify-end" data-controller="dropdown">
                        <button type="button" class="text-gray-500 group bg-white rounded-md inline-flex items-center" aria-expanded="false" data-action="click->dropdown#toggleMenu">
                          <%= inline_svg('icons/more-square.svg', class: 'w-5 h-5 fill-current text-gray-400') %>
                        </button>
                  
                        <div class="absolute z-50 right-0 top-6 px-2 max-w-xs sm:px-0 bg-white shadow-lg border border-gray-200 rounded-lg hidden" data-dropdown-target="menu">
                          <ul class="max-h-80 scroll-py-2 divide-y divide-gray-500 divide-opacity-10 overflow-y-auto">
                            <li class="p-2">
                              <ul class="text-xs text-gray-700">
                                <%= link_to edit_period_path(period), data: { turbo_frame: '_top' } do %>
                                  <li class="group flex cursor-pointer select-none items-center rounded-md px-3 py-2 hover:bg-gray-100">
                                    <%= inline_svg('icons/edit.svg', class: 'w-4 h-4 fill-current text-gray-400') %>
                                    <span class="ml-2 truncate"><%= t(:edit) %></span>
                                  </li>
                                <% end %>
                                <%= button_to period_path(period), method: :delete, data: { action: "click->confirmation#open click->dropdown#toggleMenu" }, class: 'flex w-full' do %>
                                  <li class="group flex w-full cursor-pointer select-none items-center rounded-md px-3 py-2 hover:bg-gray-100">
                                    <%= inline_svg('icons/trash.svg', class: 'w-4 h-4 fill-current text-red-400') %>
                                    <span class="ml-2 truncate text-red-500"><%= t(:delete) %></span>
                                  </li>
                                <% end %>
                              </ul>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <%= render 'shared/pagy_navbar', pagy: @pagy %>
  <% end %>
  <%= render 'shared/confirmation_modal' %>
</div>

app/views/periods/new.html.erb
<%= render 'periods/form', period: @period, categories: @categories, method: :post, btn_text: t(:create) %>

app/views/periods/run.turbo_stream.erb
<%= turbo_stream.replace "categories_list" do %>
  <%= render partial: "categories/categories_list", 
             locals: { categories: @categories,  
                       unfinished_period: @unfinished_period } %>
<% end %>

<%= turbo_stream.replace "today-timeline" do %>
  <%= render partial: "categories/timeline", locals: { categories_for_timeline: @categories_for_timeline } %>
<% end %>

app/views/periods/stop.turbo_stream.erb
<%= turbo_stream.replace "categories_list" do %>
  <%= render partial: "categories/categories_list", 
             locals: { categories: @categories, 
                       period: @period, 
                       unfinished_period: @unfinished_period } %>
<% end %>

<%= turbo_stream.replace "today-timeline" do %>
  <%= render partial: "categories/timeline", locals: { categories_for_timeline: @categories_for_timeline } %>
<% end %>

<%= turbo_stream.replace "time-for-today" do %>
  <%= render 'categories/time_for_today', total_time_for_today: @total_time_for_today %>
<% end %>