config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end  

  scope "(:locale)", locale: /en|ru/ do
    devise_for :users, controllers: { registrations: 'registrations' }
    root to: 'public#index', as: :localized_root
  end

  root to: 'categories#index'
  
  post :set_timezone, to: 'application#set_timezone'

  get "/service-worker.js", to: "service_worker#service_worker"
  get "/manifest.json", to: "service_worker#manifest"

  namespace :admin do
    resources :users, only: :index
  end

  resource :profile, only: [:show, :update]
  resource :timeline, only: [:update]

  resources :analytics, only: [:index] do
    collection do
      post '/get-chart-donut-time-categories-data', to: 'analytics#chart_donut_time_categories_data'
      post '/get-chart-bar-hourly-activity-data', to: 'analytics#chart_bar_hourly_activity_data'
    end
  end

  resources :categories, except: :index do
    patch :update_position, on: :member
    post :report_modal_content, on: :member
  end
  get :tracker, to: 'categories#index'

  resources :periods, except: :show do
    post :run, on: :collection
    post :stop, on: :collection
  end

  resources :goals

  resources :reports, param: :unique_identifier do
    post :access_report, on: :member
    post :deletion_confirmation_modal_content, on: :member
  end

  resources :subscriptions, only: [] do
    post :toggle_channel, on: :collection
  end

  post '/telegram/webhook', to: 'telegram#webhook'
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :category

  SCHEDULES = %w(daily weekly monthly)

  validates :duration, presence: true, numericality: { greater_than: 0 }
  validates :schedule, presence: true, inclusion: { in: SCHEDULES }
  validates :category_id, uniqueness: { scope: :user_id, message: I18n.t('activerecord.errors.messages.only_one_goal_per_category') }

  def hours
    duration / 60 if duration
  end

  def minutes
    duration % 60 if duration
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :set_title, only: [:index, :new, :edit]
  before_action :set_categories, only: [:new, :edit, :create, :update]

  include Authorizable

  def index
    @goals = current_user.goals.all
  end

  def show
  end

  def new
    @goal = current_user.goals.new
  end

  def edit
  end

  def create
    @goal = current_user.goals.new(goal_params)
    @goal.duration = params[:goal][:hours].to_i * 60 + params[:goal][:minutes].to_i

    if @goal.save
      redirect_to goals_path, success: t('.success')
    else
      render :new
    end
  end

  def update
    hours_to_minutes = params[:goal][:hours].to_i * 60
    minutes = params[:goal][:minutes].to_i
    total_duration = hours_to_minutes + minutes

    if @goal.update(goal_params.merge(duration: total_duration))
      redirect_to goals_path, success: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @goal.destroy!
    redirect_to goals_url, success: t('.success')
  end

  private

  def goal_params
    params.require(:goal).permit(:schedule, :category_id)
  end

  def set_goal
    @goal = current_user.goals.find(params[:id])
  end

  def set_categories
    @categories = current_user.categories.all
  end

  def set_title
    @page_title = t('.title')
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_with model: goal, method: method, data: { turbo: false } do |f| %>
  <%= render 'shared/error_messages', resource: goal %>
  <div class="md:flex items-center mt-8 grid grid-cols-1 bg-white border border-gray-200 rounded-xl shadow-md p-6">
    <div class="flex items-center gap-4">

      <%= t('.i_want_to_spend') %>

      <div class="relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :hours, t('.hours'), class: 'absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-400' %>
        <%= f.number_field :hours, value: goal.hours ? goal.hours : nil, placeholder: '2', min: "0", step: "1", class: 'block w-16 border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' %>
      </div>
    
      <div class="relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :minutes, t('.minutes'), class: 'absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-400' %>
        <%= f.number_field :minutes, value: goal.minutes ? goal.minutes : nil, placeholder: '30', min: "0", max: "59", step: "1", class: 'block w-16 border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' %>
      </div>
    </div>
    <div class="flex items-center gap-4 mt-4 md:mt-0 md:ml-4">
      <%= t('.pretext_in') %>

      <div class="relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.select :schedule, Goal::SCHEDULES.map { |schedule| [t(".#{schedule}"), schedule] }, {}, class: 'block w-44 border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' %>
      </div>
    </div>
    <div class="flex items-center gap-4 mt-4 md:mt-0 md:ml-4">
      <%= t('.pretext_on') %>

      <div class="relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.select :category_id, options_from_collection_for_select(categories, :id, :name, goal.category ? goal.category.id : nil), {}, { class: 'block w-44 border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm', placeholder: t('.choose_category') } %>
      </div>
    </div>

  </div>



  <div class="pt-8">
    <div class="flex">
      <%= link_to t(:cancel), goals_path, class: 'bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
      <%= f.submit btn_text, class: 'ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
    </div>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<% completion = ChartDataService.completion_percentage(goal) %>
<div class="relative col-span-1 border border-gray-200 shadow-md rounded-xl pl-6 pr-4 py-3">
  <div class="absolute -top-4 left-5 -mt-px inline-block px-1 bg-white text-lg font-semibold text-black tracking-tight">
    <%= goal.category.name %>
  </div>

  <div class="absolute top-0 left-0 w-3 h-full rounded-l-xl <%= goal.category.color %>"></div>
  
  <div class="flex items-center gap-4 mt-2 justify-between">
    <div class="text-sm text-gray-700">
      <%= goal.hours > 0 ? "#{ t('time.hours', count: goal.hours) } " : '' %>
      <%= goal.minutes > 0 ? "#{ goal.minutes } #{ t(:minutes) } " : '' %>
      <%= "#{ t('.pretext_in') } " %>
      <%= t(".#{goal.schedule}") %>
    </div>
    <div class="flex items-center gap-2">
      <div class="relative">
        <svg style="--fill-percent:<%= completion %>" class="pie-chart w-14 fill-gray-200 stroke-black" viewBox="0 0 20 20">
          <circle r="20" cx="10" cy="10" />
        </svg>
        <div class="absolute w-10 h-10 bg-white rounded-full top-2 left-2 text-xs font-semibold flex items-center justify-center">
          <%= completion %>%
        </div>
      </div>
      <div class="relative flex items-center justify-end" data-controller="dropdown">
        <button type="button" class="text-gray-500 group bg-white rounded-md inline-flex items-center" aria-expanded="false" data-action="click->dropdown#toggleMenu">
          <%= inline_svg('icons/more-square.svg', class: 'w-5 h-5 fill-current text-gray-400') %>
        </button>
    
        <div class="absolute z-50 right-0 top-6 px-2 max-w-xs sm:px-0 bg-white shadow-lg border border-gray-200 rounded-lg hidden" data-dropdown-target="menu">
          <ul class="max-h-80 scroll-py-2 divide-y divide-gray-500 divide-opacity-10 overflow-y-auto">
            <li class="p-2">
              <ul class="text-xs text-gray-700">
                <%= link_to edit_goal_path(goal) do %>
                  <li class="group flex cursor-pointer select-none items-center rounded-md px-3 py-2 hover:bg-gray-100">
                    <%= inline_svg('icons/edit.svg', class: 'w-4 h-4 fill-current text-gray-400') %>
                    <span class="ml-2 truncate"><%= t(:edit) %></span>
                  </li>
                <% end %>
                <%= button_to goal_path(goal), method: :delete, data: { action: "click->confirmation#open click->dropdown#toggleMenu" } do %>
                  <li class="group flex cursor-pointer select-none items-center rounded-md px-3 py-2 hover:bg-gray-100">
                    <%= inline_svg('icons/trash.svg', class: 'w-4 h-4 fill-current text-red-400') %>
                    <span class="ml-2 truncate text-red-500"><%= t(:delete) %></span>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goals/edit.html.erb
<%= render 'goals/form', goal: @goal, categories: @categories, method: :patch, btn_text: t(:update) %>

app/views/goals/index.html.erb
<div class="mt-6">
  <% if @goals.size > 0 %>
    <%= link_to new_goal_path, class: 'inline-flex items-center py-1 pl-2 pr-3 text-xs border-2 border-purple-600 text-purple-600 rounded-lg gap-1 justify-center' do %>
      <%= inline_svg('icons/add.svg', class: 'w-6 h-6 fill-current text-purple-600') %>
      <%= t('.new_goal') %>
    <% end %>
  <% end %>
</div>

<% if @goals.size == 0 %>
  <%= link_to new_goal_path, class: 'relative block w-full border-2 border-gray-300 border-dashed rounded-lg p-12 text-center hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' do %>
  <%= inline_svg('icons/folder-plus.svg', class: 'w-12 h-12 stroke-gray-500 mx-auto') %>
    <span class="mt-2 block text-sm font-medium text-gray-900"><%= t('.create_a_new_goal') %></span>
    <div class="mt-4">
      <div class="inline-flex items-center py-1 pl-2 pr-3 text-xs border-2 border-purple-600 text-purple-600 rounded-lg gap-1 justify-center">
        <%= inline_svg('icons/add.svg', class: 'w-6 h-6 fill-current text-purple-600') %>
        <%= t('.new_goal') %>
      </div>
    </div>
  <% end %>
<% else %>
  <div data-controller="confirmation" class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-4 gap-y-6 mt-8">
    <%= render @goals %>
    <%= render 'shared/confirmation_modal' %>
  </div>
<% end%>

app/views/goals/new.html.erb
<%= render 'goals/form', goal: @goal, categories: @categories, method: :post, btn_text: t(:create) %>

app/views/goals/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @goal %>

    <%= link_to "Edit this goal", edit_goal_path(@goal), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this goal", goal_path(@goal), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to goals", goals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>