config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end  

  scope "(:locale)", locale: /en|ru/ do
    devise_for :users, controllers: { registrations: 'registrations' }
    root to: 'public#index', as: :localized_root
  end

  root to: 'categories#index'
  
  post :set_timezone, to: 'application#set_timezone'

  get "/service-worker.js", to: "service_worker#service_worker"
  get "/manifest.json", to: "service_worker#manifest"

  namespace :admin do
    resources :users, only: :index
  end

  resource :profile, only: [:show, :update]
  resource :timeline, only: [:update]

  resources :analytics, only: [:index] do
    collection do
      post '/get-chart-donut-time-categories-data', to: 'analytics#chart_donut_time_categories_data'
      post '/get-chart-bar-hourly-activity-data', to: 'analytics#chart_bar_hourly_activity_data'
    end
  end

  resources :categories, except: :index do
    patch :update_position, on: :member
    post :report_modal_content, on: :member
  end
  get :tracker, to: 'categories#index'

  resources :periods, except: :show do
    post :run, on: :collection
    post :stop, on: :collection
  end

  resources :goals

  resources :reports, param: :unique_identifier do
    post :access_report, on: :member
    post :deletion_confirmation_modal_content, on: :member
  end

  resources :subscriptions, only: [] do
    post :toggle_channel, on: :collection
  end

  post '/telegram/webhook', to: 'telegram#webhook'
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_list scope: [:parent_id]

  belongs_to :user
  belongs_to :parent, class_name: 'Category', optional: true
  has_many :children, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
  has_many :periods, dependent: :destroy
  has_one :goal, dependent: :destroy
  has_many :reports, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :color, inclusion: { in: BG_COLORS.values.flatten }

  scope :sorted, -> { order(position: :asc) }

  after_save :update_level

  def self.ransackable_attributes(auth_object = nil)
    ["color", "created_at", "id", "id_value", "level", "name", "parent_id", "position", "updated_at", "user_id"]
  end

  def total_seconds
    start_date = Date.new(2000, 1, 1)
    total_seconds = CategoriesAnalyticsService.total_time_in_range(self, start_date, Time.current)
  end

  def formatted_total_time
    CategoriesAnalyticsService.seconds_to_time_format(total_seconds)
  end

  def can_have_timer?
    children.blank?
  end

  def self.any_unfinished_periods_for_user(user)
    user.categories.joins(:periods).where(periods: { end: nil }).exists?
  end  

  def descendants
    children.flat_map { |child| [child] + child.descendants }
  end

  def update_level
    new_level = parent.nil? ? 1 : parent.level + 1
    update_column(:level, new_level) if level != new_level
  
    children.each(&:update_level)
  end

  def ids_including_children
    ids = [self.id]
    children.each do |child|
      ids.concat(child.ids_including_children)
    end
    ids
  end

  def all_periods
    periods + children.flat_map(&:all_periods)
  end

  def self.all_in_current_year(user)
    start_of_year = Time.current.beginning_of_year
    today = Time.current.end_of_day

    categories_with_periods = user.categories
      .left_outer_joins(:children)
      .where(children_categories: { id: nil })
      .includes(:periods)
      .group_by(&:id)

    result = {}

    categories_with_periods.each do |category_id, categories|
      category_name = categories.first.name
      periods = categories.flat_map(&:periods)
                          .select { |period| period.start >= start_of_year }

      category_data = Hash.new { |hash, month| hash[month] = Hash.new(0) }

      periods.each do |period|
        month = period.start.strftime("%m")
        day = period.start.strftime("%d")
        category_data[month][day] = 1
      end

      result[category_name] = category_data
    end

    result.sort_by do |_, category_data| 
      -category_data.values.sum { |days| days.values.sum } 
    end.to_h
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy, :update_position]
  before_action :set_title, only: [:index, :new, :edit]
  
  include Authorizable

  def index
    @categories = current_user.categories.includes(children: :periods).where(parent_id: nil).sorted
    @unfinished_period = Category.any_unfinished_periods_for_user(current_user)
    @categories_for_timeline = current_user.categories_for_timeline

    total_seconds_today = current_user.periods.sum { |period| period.total_seconds_for_date(Time.now.to_date) }

    @total_time_for_today = CategoriesAnalyticsService.seconds_to_time_format(total_seconds_today, true)
  end

  def show
    @page_title = t('.category')

    @total_time = CategoriesAnalyticsService.seconds_to_time_format(@category.total_seconds, true)

    earliest_start = Period.where(category_id: @category.ids_including_children).minimum(:start)
    total_seconds = CategoriesAnalyticsService.average_time_per_day_in_range(@category, earliest_start, Time.now)
    @avg_time = CategoriesAnalyticsService.seconds_to_time_format(total_seconds, true)

    @time_by_months = ChartDataService.time_by_months_with_format(current_user, @category)

    @grouped_periods = Period.group_periods_by_date(@category.all_periods)
  end

  def new
    @category = current_user.categories.new
    @categories = current_user.categories.left_outer_joins(:periods).where(periods: { id: nil })
  end

  def create
    @category = current_user.categories.new(category_params)

    Category.transaction do 
      @category.increment_position

      if @category.save
        redirect_to tracker_path, success: t('.success')
      else
        @categories = current_user.categories.left_outer_joins(:periods).where(periods: { id: nil })
        render :new
      end
    end
  end

  def edit
    @categories = current_user.categories
                              .left_outer_joins(:periods)
                              .where(periods: { id: nil })
                              .where.not(id: params[:id])
  end

  def update
    @category.move_to_bottom

    if @category.update(category_params)
      redirect_to tracker_path, success: t('.success')
    else
      @categories = current_user.categories.left_outer_joins(:periods).where(periods: { id: nil })
      render :edit
    end 
  end

  def destroy
    return if @category.blank?
    
    if @category.destroy
      redirect_to tracker_path, success: t('.success')
    else
      redirect_to tracker_path, danger: t('.error')
    end
  end

  def update_position
    new_position = params[:category][:position].to_i

    ActiveRecord::Base.transaction do
      @category.insert_at(new_position)
    end
  
    if @category.errors.empty?
      head :ok
    else
      render json: { ok: false, errors: @category.errors.full_messages }, status: :unprocessable_entity
    end
  rescue => e
    render json: { ok: false, errors: [e.message] }, status: :unprocessable_entity
  end

  def report_modal_content
    @category = Category.find(params[:id])
    @report = params[:report_id].present? ? Report.find(params[:report_id]) : Report.new
    render partial: 'categories/report_modal_content', locals: { category: @category, report: @report }
  end

  private

  def category_params
    params.require(:category).permit(:name, :parent_id, :color, :position)
  end

  def find_category
    @category = current_user.categories.find(params[:id])
  end

  def set_title
    @page_title = t('.title')
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def render_categories(categories, unfinished_period)
    content_tag(:div, class: "categories-list", data: { controller: "sortable", sortable_resource_name_value: "category" }) do
      categories.sorted.each do |category|
        concat(render(partial: 'categories/category_card', locals: { category: category, unfinished_period: unfinished_period }))
      end
    end
  end

  def active_period_by_category(category)
    last_period = category.periods.order(start: :desc).first
    last_period&.end ? nil : last_period
  end

  def indicator_properties(value)
    if value > 0
      { color: 'green', text: 'Increased by', icon_filename: 'icons/increased.svg' }
    elsif value < 0
      { color: 'red', text: 'Decreased by', icon_filename: 'icons/decreased.svg' }
    else
      { color: 'gray', text: 'No change', icon_filename: nil }
    end
  end
end

app/views/categories/_categories_list.html.erb
<div id="categories_list" aria-label="card" class="tree pt-2" data-controller="confirmation">
  <div aria-label="content" class="grid gap-2.5">
    <%= render_categories(categories, unfinished_period) %>
  </div>

  <%= render 'shared/confirmation_modal' %>
</div>

app/views/categories/_category_card.html.erb
<div data-sortable-update-url="<%= update_position_category_path(category) %>" data-sortable-param-name-value="position" <%= category.children.count > 0 ? 'class="relative parent-category-container"'.html_safe : '' %> data-position="<%= category.position %>">
  <div class="mt-2">
    <% if category.level === 1 && category.children.present? %>
      <div class="pb-1 pt-4" id="category-card-<%= category.id %>">
        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <div class="drag-handle p-1 cursor-grab w-8 h-8 flex items-center justify-center">
              <%= icon('grip-vertical', class: 'w-5 h-5 text-gray-200') %>
            </div>
            <div class="w-3 h-3 rounded-full <%= category.color == 'bg-white' ? 'bg-gray-100' : category.color %>"></div>
            <div class="text-xl font-semibold text-black ml-2">
              <%= link_to category.name, category_path(category) %>
            </div>
          </div>
          <div class="flex items-center">
            <div class="text-gray-700 text-sm"><%= category.formatted_total_time %></div>
            <%= render 'categories/more_dropdown_btn', category: category %>
          </div>
        </div>
      </div>
      <%= render_categories(category.children, unfinished_period) if category.children.any? %>
    <% elsif category.level === 1 %>
      <div class="mt-6">
        <%= render 'categories/category_core', category: category, period: active_period_by_category(category), unfinished_period: unfinished_period %>
      </div>
    <% else %>
      <%= render 'categories/category_core', category: category, period: active_period_by_category(category), unfinished_period: unfinished_period %>
      <div class="ml-6 mt-2">
        <%= render_categories(category.children, unfinished_period) if category.children.any? %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_category_core.html.erb
<div class="flex items-center">
  <div class="drag-handle p-1 cursor-grab w-8 h-8 flex items-center justify-center">
    <%= icon('grip-vertical', class: 'w-5 h-5 text-gray-200') %>
  </div>
  <div class="flex flex-col flex-grow">
    <div class="relative bg-white rounded p-2" id="category-card-<%= category.id %>">
      <div class="absolute top-0 left-0 w-2 h-full rounded-l <%= category.color == 'bg-white' ? 'bg-gray-200' : category.color %>"></div>
      <div class="flex items-center justify-between">
        <div class="ml-4">
          <div class="text-md font-medium text-black leading-4">
            <%= link_to category.name, category_path(category) %>
            <div class="text-gray-500 text-sm font-normal"><%= category.formatted_total_time %></div>
          </div>
        </div>
        <div class="flex items-center">
          <% if period %>
            <%= form_with url: '/periods/stop', method: :post, data: { turbo_stream: true, controller: "timer", action: 'submit->timer#showSpinner' }, class: "flex items-center p-1 text-sm gap-1 justify-between" do |f| %>
              <%= f.hidden_field :category_id, name: 'period[category_id]', value: category.id %>
              <%= f.hidden_field :start, name: 'period[start]', value: period.start_in_zone, id: 'period_start' %>
              <%= f.hidden_field :period_id, value: period.id %>
              
              <div class="flex items-center mr-2 text-gray-400" data-timer-target="clock">
                <span data-timer-target="output">00:00:00</span>
              </div>
              <%= button_tag type: 'submit', id: "category-stop-#{category.id}", class: 'flex items-center md:mx-2', data: { timer_target: 'button' } do %>
                <%= inline_svg('icons/stop-solid.svg', class: 'w-6 h-6 text-black') %>
                <span class="text-sm ml-2 hidden md:block"><%= t('.stop') %></span>
              <% end %>
              <div class="dot-pulse-spinner md:mx-2 hidden" data-timer-target="spinner"><div class="dot"></div></div>
            <% end %>
          <% else %>
            <% if category.can_have_timer? && !unfinished_period %>
              <%= form_with url: '/periods/run', method: :post, data: { turbo_stream: true, controller: 'timer', action: 'submit->timer#showSpinner' } do |f| %>
                <%= f.hidden_field :category_id, value: category.id, name: 'period[category_id]' %>
                <%= button_tag type: 'submit', id: "category-start-#{category.id}", class: 'flex items-center md:mx-2', data: { timer_target: 'button' } do %>
                  <%= inline_svg('icons/play-solid.svg', class: 'w-6 h-6 text-black') %>
                  <span class="text-sm ml-2 hidden md:block"><%= t('.start') %></span>
                <% end %>
                <div class="dot-pulse-spinner md:mx-2 hidden" data-timer-target="spinner"><div class="dot"></div></div>
              <% end %>
            <% end %>
          <% end %>
          <%= render 'categories/more_dropdown_btn', category: category %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="mt-8 max-w-3xl mx-auto grid grid-cols-1 gap-6 lg:max-w-7xl lg:grid-flow-col-dense lg:grid-cols-3">
  <div class="space-y-6 lg:col-start-1 lg:col-span-2">
    <%= form_with model: category, method: method, data: { turbo: false } do |f| %>
      <%= render 'shared/error_messages', resource: category %>
      <div class="relative mt-8 border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :name, t('.name_label'), class: "absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-900" %>
        <%= f.text_field :name, class: 'block border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm', placeholder: t('.name_placeholder') %>
      </div>
      <div class="relative mt-8 border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :parent_id, t('.parent_label'), class: "absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-900" %>
        <%= f.select :parent_id, options_for_select([[t(:none_option), ""]]) + options_from_collection_for_select(categories, :id, :name, category.parent&.id), {}, class: 'block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' %>
      </div>
      
      <div data-controller="color-picker"
           data-color-picker-text-colors-value="<%= TEXT_COLORS.to_json %>" 
           class="text-sm">
        <div data-action="click->color-picker#toggleColorModal" data-color-picker-target="currentColor" class="px-6 py-2 rounded-lg cursor-pointer inline-block border border-gray-300 mt-4 <%= category.color || 'bg-white' %> <%= TEXT_COLORS[category.color] || 'text-gray-950' %>">
          <%= t('.choose_color') %>
        </div>
        <input type="hidden" name="category[color]" data-color-picker-target="colorInput" value="<%= category.color || 'bg-white' %>">
      
        <div data-color-picker-target="colorModal" class="absolute border border-gray-300 rounded-lg p-2 bg-white z-10 hidden">
          <% BG_COLORS.each do |color, shades| %>
            <div>
              <% shades.each do |shade| %>
                <div data-action="click->color-picker#selectColor" class="w-7 h-5 rounded-lg cursor-pointer inline-block border border-gray-300 <%= shade %>" data-value="<%= shade %>"></div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    
      <div class="shrink-0 mt-8">
        <%= f.submit btn_text, class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_modal.html.erb
<div id="modal-overlay" data-modal-target="overlay" class="hidden opacity-0 z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true" data-action="click->modal#hide"></div>
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
    <div id="modal-panel" data-modal-target="panel" class="relative hidden opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95 align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
      <div data-modal-target="content">
        <div id="modal_content">
          <!-- Содержимое модального окна будет загружено сюда -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_more_dropdown_btn.html.erb
<% show_page ||= false %>
<div class="relative flex items-center" data-controller="dropdown">
  <button type="button" class="text-gray-500 group rounded-md inline-flex items-center pl-2" aria-expanded="false" data-action="click->dropdown#toggleMenu">
    <%= inline_svg('icons/ellipsis-vertical.svg', class: "#{ show_page ? 'w-8 h-8' : 'w-6 h-6' } fill-current text-black") %>
  </button>

  <div class="absolute z-50 right-0 top-6 px-2 max-w-xs sm:px-0 bg-white shadow-lg border border-gray-200 rounded-lg hidden" data-dropdown-target="menu">
    <ul class="max-h-80 scroll-py-2 divide-y divide-gray-500 divide-opacity-10 overflow-y-auto">
      <li class="p-2">
        <ul class="text-xs text-gray-700">
          <% unless show_page %>
            <%= link_to category_path(category) do %>
              <li class="group flex cursor-pointer select-none items-center rounded-md px-3 py-2 hover:bg-gray-100">
                <%= inline_svg('icons/eye.svg', class: 'w-4 h-4 fill-current text-gray-400') %>
                <span class="ml-2 flex-auto truncate"><%= t('.view_details') %></span>
              </li>
            <% end %>
          <% end %>
          <%= link_to edit_category_path(category) do %>
            <li class="group flex cursor-pointer select-none items-center rounded-md px-3 py-2 hover:bg-gray-100">
              <%= inline_svg('icons/edit.svg', class: 'w-4 h-4 fill-current text-gray-400') %>
              <span class="ml-2 flex-auto truncate"><%= t(:edit) %></span>
            </li>
          <% end %>
          <%= link_to "javascript:void(0)", data: { contentUrl: report_modal_content_category_path(category), action: "click->modal#show click->dropdown#toggleMenu" } do %>
            <li class="group flex cursor-pointer select-none items-center rounded-md px-3 py-2 hover:bg-gray-100">
              <%= inline_svg('icons/clipboard-text.svg', class: 'w-4 h-4 fill-current text-gray-400') %>
              <span class="ml-2 flex-auto truncate"><%= t('.create_report') %></span>
            </li>
          <% end %>
          <%= button_to category_path(category), method: :delete, data: { action: "click->confirmation#open click->dropdown#toggleMenu" }, class: 'group flex w-full text-left cursor-pointer select-none items-center rounded-md px-3 py-2 hover:bg-gray-100' do %>
              <%= inline_svg('icons/trash.svg', class: 'w-4 h-4 fill-current text-red-400') %>
              <span class="ml-2 flex-auto truncate text-red-500"><%= t(:delete) %></span>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/categories/_report_modal_content.html.erb
<div id="modal_content">
  <% method = report.start_date.present? ? :patch : :post %>
  <%= form_with model: report, method: method do |f| %>
    <div>
      <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
        <%= inline_svg('icons/note-favorite.svg', class: 'h-6 w-6 text-green-600') %>
      </div>
      <div class="mt-3 text-center sm:mt-5">
        <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title"><%= category.name %></h3>
        <div class="mt-2">
          <p class="text-sm text-gray-500"><%= t('.new_report_text') %></p>
        </div>
      </div>
    </div>
    <div class="mt-4">
      <%= render 'shared/error_messages', resource: report %>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-8 mb-4">
      <div class="relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :start_date, t('.start'), class: 'absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-900' %>
        <%= f.text_field :start_date, data: { controller: 'flatpickr' }, value: report.start_date ? format_utc_datetime(report.start_date.in_time_zone) : nil, class: 'block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' %>
      </div>
    
      <div class="relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
        <%= f.label :end_date, t('.end'), class: 'absolute -top-2 left-2 -mt-px inline-block px-1 bg-white text-xs font-medium text-gray-900' %>
        <%= f.text_field :end_date, data: { controller: 'flatpickr' }, value: report.end_date ? format_utc_datetime(report.end_date.in_time_zone) : nil, class: 'block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm' %>
      </div>
      <%= f.hidden_field :category_id, value: category.id %>
    </div>
    <div class="mt-12 mb-4 flex flex-wrap sm:flex-nowrap items-center justify-center gap-4 px-4">
      <button data-action="click->modal#hide" type="button" class="w-24 inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:col-start-1 sm:text-sm"><%= t(:cancel) %></button>
      <button type="submit" class="w-40 inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:col-start-2 sm:text-sm"><%= t(:save) %></button>
    </div>
  <% end %>
</div>

app/views/categories/_time_for_today.html.erb
<h3 id="time-for-today" class="pl-6 flex text-sm items-center text-neutral-500">
  <%= inline_svg('icons/clock.svg', class: "w-4 h-4 fill-current text-gray-400 mr-2 mt-0.5") %>
  <%= total_time_for_today %>&nbsp;<%= t('.spent_today') %>
</h3>

app/views/categories/_timeline.html.erb
<div id="today-timeline" class="px-4 pt-2 pb-3 rounded-lg mt-4 border border-neutral-200">
  <div class="text-left mb-2">
    <span class="text-xs text-black"><%= t('.today') %></span>
  </div>
  <div 
    data-controller="timeline" 
    data-action="stimulus:load->timeline#updateCurrentTimeLine" 
    class="relative h-2 border border-gray-200 rounded-full bg-gray-100">

    <% categories_for_timeline.each do |category| %>
      <% category.periods.each do |period| %>
        <% period_data = PeriodSerializer.new(period).as_json %>
          <% if period.end.blank? %>
            <div 
              class="group absolute h-2 rounded-l-full min-w-1"
              data-timeline-target="currentPeriod"
              style="left: <%= outside_today?(period) ? 0 : period_data[:start_percentage] %>%;">
              <div class="absolute rounded-l-full h-1.5 w-full overflow-hidden">
                <div class="stripe"></div>
              </div>
              <span class="pointer-events-none absolute bg-black text-2xs leading-4 text-white rounded-md px-3 py-1 -top-12 left-0 w-max opacity-0 transition-opacity group-hover:opacity-100">
                <%= t('.category') %>: <%= category.name %><br/>
                <%= t('.start') %>: <%= period.start_in_zone %>
              </span>
            </div>
          <% elsif period.end >= Time.zone.now.beginning_of_day %>
            <div 
              class="completed-period group absolute h-full <%= category.color %> rounded-full min-w-1 border <%= adjust_color_intensity('border', category.color, 300) %>"
              style="left: <%= period_data[:start_percentage] %>%; width: <%= period_data[:width_percentage] %>%;">

              <span class="pointer-events-none absolute bg-black text-2xs leading-4 text-white rounded-md px-3 py-1 -top-12 left-0 w-max opacity-0 transition-opacity group-hover:opacity-100">
                <%= t('.category') %>: <%= category.name %><br/>
                <%= t('.time') %>: <%= period.formatted_time %>
              </span>
            </div>
          <% end %>
      <% end %>
    <% end %>
    <div data-timeline-target="currentTimeLine" class="absolute bg-black" style="width: 1px; top: -5px; bottom: -5px;"></div>
  </div>
  <div class="flex justify-between w-full text-2xs text-neutral-600 mt-2 md:hidden">
    <% formatted_hours(4).each do |formatted_hour| %>
      <span><%= formatted_hour %></span>
    <% end %>
  </div>

  <div class="hidden md:flex justify-between w-full text-2xs text-neutral-600 mt-2">
    <% formatted_hours(2).each do |formatted_hour| %>
      <span><%= formatted_hour %></span>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render 'categories/form', category: @category, categories: @categories, method: :patch, btn_text: t(:update) %>

app/views/categories/index.html.erb
<%= render 'categories/timeline', categories_for_timeline: @categories_for_timeline %>


<div class="mt-6 sm:flex sm:items-center sm:justify-between">
  <div class="flex items-center text-xs leading-6 text-neutral-700">
    <h2 class="text-lg text-neutral-600 font-semibold"><%= t('.categories') %></h2>
    <%= render 'categories/time_for_today', total_time_for_today: @total_time_for_today %>
  </div>
  <div class="mt-3 sm:mt-0 sm:ml-4">
    <% if @categories.size > 0 %>
      <%= link_to new_category_path, class: 'inline-flex items-center py-1 pl-2 pr-3 text-xs border-2 border-purple-600 text-purple-600 rounded-lg gap-1 justify-center' do %>
        <%= inline_svg('icons/add.svg', class: 'w-6 h-6 fill-current text-purple-600') %>
        <%= t('.new_category') %>
      <% end %>
    <% end %>
  </div>
</div>

<% if @categories.size == 0 %>
  <%= link_to new_category_path, class: 'relative block w-full border-2 border-gray-300 border-dashed rounded-lg mt-4 p-12 text-center hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' do %>
  <%= inline_svg('icons/folder-plus.svg', class: 'w-12 h-12 stroke-gray-500 mx-auto') %>
    <span class="mt-2 block text-sm font-medium text-gray-900"><%= t('.create_a_new_category') %></span>
    <div class="mt-4">
      <div class="inline-flex items-center py-1 pl-2 pr-3 text-xs border-2 border-purple-600 text-purple-600 rounded-lg gap-1 justify-center">
        <%= inline_svg('icons/add.svg', class: 'w-6 h-6 fill-current text-purple-600') %>
        <%= t('.new_category') %>
      </div>
    </div>
  <% end %>
<% else %>
  <div data-controller="modal">
    <%= render 'categories/categories_list', categories: @categories, unfinished_period: @unfinished_period %>
    <%= render 'shared/modal' %>
  </div>
<% end%>

app/views/categories/new.html.erb
<%= render 'categories/form', category: @category, categories: @categories, method: :post, btn_text: t(:create) %>