config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end  

  scope "(:locale)", locale: /en|ru/ do
    devise_for :users, controllers: { registrations: 'registrations' }
    root to: 'public#index', as: :localized_root
  end

  root to: 'categories#index'
  
  post :set_timezone, to: 'application#set_timezone'

  get "/service-worker.js", to: "service_worker#service_worker"
  get "/manifest.json", to: "service_worker#manifest"

  namespace :admin do
    resources :users, only: :index
  end

  resource :profile, only: [:show, :update]
  resource :timeline, only: [:update]

  resources :analytics, only: [:index] do
    collection do
      post '/get-chart-donut-time-categories-data', to: 'analytics#chart_donut_time_categories_data'
      post '/get-chart-bar-hourly-activity-data', to: 'analytics#chart_bar_hourly_activity_data'
    end
  end

  resources :categories, except: :index do
    patch :update_position, on: :member
    post :report_modal_content, on: :member
  end
  get :tracker, to: 'categories#index'

  resources :periods, except: :show do
    post :run, on: :collection
    post :stop, on: :collection
  end

  resources :goals

  resources :reports, param: :unique_identifier do
    post :access_report, on: :member
    post :deletion_confirmation_modal_content, on: :member
  end

  resources :subscriptions, only: [] do
    post :toggle_channel, on: :collection
  end

  post '/telegram/webhook', to: 'telegram#webhook'
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :start_date, :end_date, :unique_identifier, :pass, presence: true
  validates :unique_identifier, uniqueness: true

  before_validation :generate_unique_identifier, on: :create

  def to_param
    unique_identifier
  end
  
  private

  def generate_unique_identifier
    self.unique_identifier = loop do
      token = SecureRandom.uuid
      break token unless Report.exists?(unique_identifier: token)
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout 'public', only: [:show]
  before_action :set_public_locale, only: [:show]

  def index
    @reports = current_user.reports.order(created_at: :desc)
  end

  def create
    @category = current_user.categories.find(report_params[:category_id])
    @report = current_user.reports.new(report_params)
    @report.pass = SecureRandom.hex(5)

    start_date = @report.start_date
    end_date = @report.end_date
    category_ids = @category.ids_including_children
    periods = current_user.periods.where(category_id: category_ids).where('"start" <= ? AND "end" >= ?', end_date, start_date)  
    
    if periods.exists?
      if @report.save
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(
              'modal_content',
              partial: 'reports/report_url',
              locals: { report: @report, category: @category }
            )
          end
        end
      else
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(
              'modal_content',
              partial: 'categories/report_modal_content',
              locals: { report: @report, category: @category }
            )
          end
        end
      end
    else
      @report.errors.add(:base, t('.no_data'))
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'modal_content',
            partial: 'categories/report_modal_content',
            locals: { report: @report, category: @category }
          )
        end
      end
    end
  end

  def update
    @category = current_user.categories.find(report_params[:category_id])
    @report = current_user.reports.find_by!(unique_identifier: params[:unique_identifier])

    start_date = Date.parse(report_params[:start_date])
    end_date = Date.parse(report_params[:end_date])
    category_ids = @category.ids_including_children
    periods = current_user.periods.where(category_id: category_ids).where('"start" <= ? AND "end" >= ?', end_date, start_date)  
    
    if periods.exists?
      if @report.update(report_params)
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(
              'modal_content',
              partial: 'reports/report_url',
              locals: { report: @report, category: @category }
            )
          end
        end
      else
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(
              'modal_content',
              partial: 'categories/report_modal_content',
              locals: { report: @report, category: @category }
            )
          end
        end
      end
    else
      @report.errors.add(:base, t('.no_data'))
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'modal_content',
            partial: 'categories/report_modal_content',
            locals: { report: @report, category: @category }
          )
        end
      end
    end
  end

  def show 
  end

  def access_report
    @report = current_user.reports.find_by!(unique_identifier: params[:unique_identifier])

    if @report.pass == params[:pass]
      category_ids = @report.category.ids_including_children
      periods = @report.user.periods.where(category_id: category_ids).order(start: :desc)
      start_date = @report.start_date
      end_date = @report.end_date
      @grouped_periods = current_user.periods.group_periods_by_date_with_limits(periods, start_date, end_date)

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'report-content',
            partial: 'reports/report',
            locals: { report: @report, grouped_periods: @grouped_periods }
          )
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'report-content',
            partial: 'reports/password',
            locals: { report: @report, error: true }
          )
        end
      end
    end
  end

  def deletion_confirmation_modal_content
    @report = current_user.reports.find_by!(unique_identifier: params[:unique_identifier])
    render partial: 'reports/deletion_confirmation_modal_content', locals: { report: @report }
  end

  def destroy
    @report = current_user.reports.find_by!(unique_identifier: params[:unique_identifier])
    @report_id = @report.id
    @report.destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(
            'report-deletion-content',
            partial: 'reports/report_successfully_deleted'
          ),
          turbo_stream.remove("report-#{@report_id}")
        ]
      end
    end
  end

  private

  def report_params
    params.require(:report).permit(:user_id, :category_id, :start_date, :end_date, :pass)
  end

  def set_public_locale
    @report = Report.find_by!(unique_identifier: params[:unique_identifier])
    I18n.locale = @report.user.try(:locale) || I18n.default_locale
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def report_period_range(report)
    "#{format_utc_datetime(report.start_date)} - #{format_utc_datetime(report.end_date)}"
  end

  def filled_days_count(months_data)
    months_data.sum { |_, days| days.sum { |_, count| count.to_i } }
  end

  def day_color_by_status(status, date)
    if status == 1
      'violet-600'
    elsif status == 0 && date <= Time.current.to_date
      'gray-300'
    else
      'gray-100'
    end
  end
end

app/views/reports/_deletion_confirmation_modal_content.html.erb
<div id="report-deletion-content">
  <%= form_with model: report, method: :delete do |f| %>
  <div class="bg-white">
    <div class="sm:flex sm:items-start">
      <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
        <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
      </div>
      <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
        <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title"><%= t('.report_deletion') %></h3>
        <div class="mt-2">
          <p class="text-sm text-gray-500"><%= t('.report_deletion_text') %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-4 sm:flex sm:flex-row-reverse">
    <button type="submit" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm"><%= t(:delete) %></button>
    <button data-action="click->modal#hide" type="button" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"><%= t(:cancel) %></button>
  </div>
  <% end %>
</div>

app/views/reports/_password.html.erb
<% error ||= false %>
<div id="report-content">
  <div class="bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:p-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900"><%= t('.enter_password') %></h3>
      <div class="mt-2 max-w-xl text-sm text-gray-500">
        <p><%= t('.enter_password_text') %></p>
      </div>
      <% if error %>
        <div class="mt-2 max-w-xl text-sm text-red-500">
          <p><%= t('.wrong_password') %></p>
        </div>
      <% end %>
      <%= form_with url: access_report_report_path(report), method: :post, class: 'mt-5 sm:flex sm:items-center', data: { turbo: true, turbo_stream: true } do |f| %>
        <div class="w-full sm:max-w-xs">
          <%= f.text_field :pass, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md' %>
        </div>
        <button type="submit" class="mt-3 w-full inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"><%= t('.confirm') %></button>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/_report.html.erb
<div id="report-content" class="w-full">
  <div class="max-w-xl mx-auto py-8">
    <div>
      <div class="text-xl font-bold"><%= t('.report') %></div>
      <div class="text-sm"><b><%= t('.user') %>:</b> <%= report.user.email %></div>
      <div class="text-sm"><b><%= t('.period') %>:</b> <%= report_period_range(report) %></div>
    </div>
    <div class="mt-4 flex flex-col">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table id="periods_list" class="min-w-full">
              <thead class="bg-white">
                <tr>
                  <th scope="col" width="20%" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%= t('.date')%></th>
                  <th scope="col" width="20%" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.category')%></th>
                  <th scope="col" width="20%" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.period') %></th>
                  <th scope="col" width="20%" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.duration')%></th>
                </tr>
              </thead>
              <tbody class="bg-white">
                <% total_seconds = 0 %>
                <% grouped_periods.each do |date, periods| %>
                  <% total_seconds += daily_periods_seconds(periods, date) %>
                  <% periods.each do |period| %>
                    <tr class="border-t border-gray-200">
                      <td class="relative py-3 pl-4 pr-3 text-xs text-gray-900 sm:pl-6">
                        <%= date.strftime('%d.%m.%Y') %>
                      </td>
                      <td class="whitespace-nowrap px-3 py-3 text-left text-xs text-gray-500">
                        <div class="flex items-center text-left">
                          <%= period.category.name %>
                          <% if period.start.to_date != period.actual_end.to_date %>
                            <div class="group relative">
                              <%= inline_svg('icons/arrow-3.svg', class: 'w-3 h-3 fill-current text-red-400 ml-2') %>
                              <span class="pointer-events-none absolute bg-black text-2xs leading-4 text-white rounded-md px-3 py-1 left-0 bottom-6 w-60 opacity-0 transition-opacity group-hover:opacity-100">
                                <%= t('.long_period_explanation') %>
                              </span>
                            </div>
                          <% end %>
                        </div>
                      </td>
                      <td class="whitespace-nowrap px-3 py-3 text-left text-xs text-gray-500">
                        <%= format_period_start(period, date) %> - <%= format_period_end(period, date) %>
                      </td>
                      <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500">
                        <div class="flex items-center">
                          <%= inline_svg('icons/clock.svg', class: 'w-4 h-4 fill-current text-purple-600 mr-2') %>
                          <%= humanize_time_from_seconds(daily_periods_seconds([period], date)) %>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
                <tr class="border-t border-gray-200 bg-yellow-100">
                  <th colspan="2" scope="colgroup" class="px-4 py-4 text-left text-sm font-semibold text-gray-900 sm:px-6">
                    <%= t('.total') %>
                  </th>
                  <th colspan="2" class="px-4 py-4 text-right text-xs font-normal text-gray-900 sm:px-6">
                    <%= humanize_time_from_seconds(total_seconds) %>
                  </th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/_report_successfully_deleted.html.erb
<div id="report-deletion-content">
  <div>
    <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
      <svg class="h-6 w-6 text-green-600" x-description="Heroicon name: outline/check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
      </svg>
    </div>
    <div class="mt-3 text-center sm:mt-5">
      <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title"><%= t('.report_deleted') %></h3>
    </div>
  </div>
  <div class="mt-12 mb-4 flex flex-wrap sm:flex-nowrap items-center justify-center">
    <button data-action="click->modal#hide" type="button" class="mt-3 w-24 inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:col-start-1 sm:text-sm"><%= t(:close) %></button>
  </div>
</div>

app/views/reports/_report_url.html.erb
<div id="modal_content">
  <div>
    <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
      <svg class="h-6 w-6 text-green-600" x-description="Heroicon name: outline/check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
      </svg>
    </div>
    <div class="mt-3 text-center sm:mt-5">
      <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title"><%= t('.created', category: category.name) %></h3>
      <div class="mt-2">
        <p class="text-sm text-gray-500"><%= t('.report_url_text_html') %></p>
      </div>
    </div>
  </div>
  <div data-controller="clipboard" data-clipboard-success-content-value="<%= t(:copied) %>" class="mt-8">
    <label for="link" class="block text-sm font-medium text-gray-700"><%= t('.link') %></label>
    <div class="mt-1 flex rounded-md shadow-sm">
      <div class="relative flex items-stretch flex-grow focus-within:z-10">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <%= inline_svg('icons/link.svg', class: 'h-5 w-5 text-gray-400') %>
        </div>
        <%= text_field_tag :link, report_url(report), class: 'focus:ring-indigo-500 focus:border-indigo-500 block w-full rounded-none rounded-l-md pl-10 sm:text-sm border-gray-300', disabled: true, data: { clipboard_target: "source" } %>
      </div>
      <button data-action="clipboard#copy" data-clipboard-target="button" type="button" class="-ml-px relative inline-flex items-center space-x-2 px-4 py-2 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
        <%= inline_svg('icons/clipboard.svg', class: 'h-5 w-5 text-gray-400') %>
        <span><%= t('.copy') %></span>
      </button>
    </div>
  </div>
  <div data-controller="clipboard" data-clipboard-success-content-value="<%= t(:copied) %>" class="mt-4">
    <label for="pass" class="block text-sm font-medium text-gray-700"><%= t('.password') %></label>
    <div class="mt-1 flex rounded-md shadow-sm">
      <div class="relative flex items-stretch flex-grow focus-within:z-10">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <%= inline_svg('icons/key.svg', class: 'h-5 w-5 text-gray-400') %>
        </div>
        <%= text_field_tag :pass, report.pass, class: 'focus:ring-indigo-500 focus:border-indigo-500 block w-full rounded-none rounded-l-md pl-10 sm:text-sm border-gray-300', disabled: true, data: { clipboard_target: "source" } %>
      </div>
      <button data-action="clipboard#copy" data-clipboard-target="button" type="button" class="-ml-px relative inline-flex items-center space-x-2 px-4 py-2 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
        <%= inline_svg('icons/clipboard.svg', class: 'h-5 w-5 text-gray-400') %>
        <span><%= t('.copy') %></span>
      </button>
    </div>
  </div>
  <div class="mt-12 mb-4 flex flex-wrap sm:flex-nowrap items-center justify-center">
    <button data-action="click->modal#hide" type="button" class="mt-3 w-24 inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:col-start-1 sm:text-sm"><%= t(:close) %></button>
  </div>
</div>

app/views/reports/index.html.erb
<div class="sm:flex sm:items-center">
  <div class="sm:flex-auto">
    <h1 class="text-2xl font-semibold text-gray-900"><%= t('.reports') %></h1>
  </div>
</div>
<div data-controller="modal" class="mt-8 flex flex-col">
  <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
      <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
        <table id="reports_list" class="min-w-full divide-y divide-gray-300">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%= t('.created') %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.category') %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.period') %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.link') %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%= t('.password') %></th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6"></th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
            <% @reports.each do |report| %>
              <tr id="report-<%= report.id %>">
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                  <%= format_utc_datetime(report.created_at) %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= report.category.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= report_period_range(report) %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <div data-controller="clipboard" data-clipboard-success-content-value="<%= t(:copied) %>">
                    <div class="flex rounded-md shadow-sm">
                      <div class="relative flex items-stretch flex-grow focus-within:z-10">
                        <%= text_field_tag :link, report_url(report), class: 'min-w-32 focus:ring-indigo-500 focus:border-indigo-500 block w-full rounded-none rounded-l-md sm:text-sm border-gray-300', disabled: true, data: { clipboard_target: "source" } %>
                      </div>
                      <button data-action="clipboard#copy" data-clipboard-target="button" type="button" class="-ml-px relative inline-flex items-center space-x-2 px-2 py-1 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                        <%= inline_svg('icons/clipboard.svg', class: 'h-5 w-5 text-gray-400') %>
                      </button>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <div data-controller="clipboard" data-clipboard-success-content-value="<%= t(:copied) %>">
                    <div class="flex rounded-md shadow-sm">
                      <div class="relative flex items-stretch flex-grow focus-within:z-10">
                        <%= text_field_tag :pass, report.pass, class: 'min-w-32 focus:ring-indigo-500 focus:border-indigo-500 block w-full rounded-none rounded-l-md sm:text-sm border-gray-300', disabled: true, data: { clipboard_target: "source" } %>
                      </div>
                      <button data-action="clipboard#copy" data-clipboard-target="button" type="button" class="-ml-px relative inline-flex items-center space-x-2 px-2 py-1 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                        <%= inline_svg('icons/clipboard.svg', class: 'h-5 w-5 text-gray-400') %>
                      </button>
                    </div>
                  </div>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <div class="flex items-center justify-end gap-2">
                    <%= link_to "javascript:void(0)", data: { contentUrl: report_modal_content_category_path(report.category, report_id: report.id), action: "click->modal#show click->dropdown#toggleMenu" } do %>
                      <%= inline_svg('icons/edit.svg', class: 'w-5 h-5 fill-current text-gray-400') %>
                    <% end %>
                    <%= link_to "javascript:void(0)", data: { contentUrl: deletion_confirmation_modal_content_report_path(report), action: "click->modal#show click->dropdown#toggleMenu" } do %>
                      <%= inline_svg('icons/trash.svg', class: 'w-5 h-5 fill-current text-red-400') %>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%= render 'shared/modal' %>
</div>

app/views/reports/show.html.erb
<div class="w-full min-h-96 flex items-center justify-center">
  <%= render 'reports/password', report: @report %>
</div>